<div class="row">
    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12  col-lg-offset-4 col-md-offset-3 col-sm-offset-3">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Escolha uma opção</h3>
            </div>
            <div class="panel-body center">
                <a class="btn btn-primary" href="{$hostPath}project/start">Novo</a>
                <a class="btn btn-info" href="{$hostPath}project/import">Importar</a>
            </div>
        </div>
    </div>
</div>