<div class="row">
    <div class="col-lg-6   col-lg-offset-3">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Novo Projeto</h3>
            </div>
            <div class="panel-body">
                <form action="{$hostPath}project/startSave" role="form" method="post" class="form-horizontal">
                    <div class="form-group">
                        <label for="nom-projeto" class="col-lg-2 control-label">Nome</label>
                        <div class="col-lg-10">
                            <input type="text" required name="nom-projeto" class="form-control" id="nom-projeto" placeholder="Nome" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="des-projeto" class="col-lg-2 control-label">Descrição</label>
                        <div class="col-lg-10">
                            <textarea placeholder="Descrição" name="des-projeto" class="form-control" id="des-projeto" rows="1"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="des-caminho" class="col-lg-2 control-label">Caminho</label>
                        <div class="col-lg-10">
                            <input type="text" required name="des-caminho" class="form-control" id="des-caminho" placeholder="Caminho absoluto" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="frk-idioma-default" class="col-lg-2 control-label">Idioma</label>
                        <div class="col-lg-10">
                            <select required name="frk-idioma-default" class="form-control" id="frk-idioma-default">
                                <option>Selecione</option>
                                <option value="pt_BR">Português (Brasil)</option>
                                <option value="en_US">Inglês (EUA)</option>
                            </select>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary pull-right"><span class="glyphicon glyphicon-chevron-down"></span> Criar</button>
                </form>
            </div>
        </div>
    </div>
</div>