<script>var lang = '{$lang}', project = '{$nomProjeto}';</script>
<div class="col-lg-10 col-md-10 col-sm-12 col-xs-12  col-lg-offset-1 col-md-offset-1">
    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="titulo">{$this->translate('Tradução - ')} <strong>{$lang}</strong></span>
            <div class="pull-right">
                <div class="btn-group">
                    <button type="button" class="btn btn-sm btn-primary"><span class="glyphicon glyphicon-cog"></span></button>
                    <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li><a data-toggle="modal" href="#mdlGoogleAll"><span class="glyphicon glyphicon-globe"></span> {$this->translate('Tradução automática')}</a></li>
                        <li class="divider"></li>
                        <li><a href="#" id="btn-save-po"><span class="glyphicon glyphicon-download-alt"></span> {$this->translate('Exportar')} .PO</a></li>
                        <li><a href="#" id="btn-save-mo"><span class="glyphicon glyphicon-download-alt"></span> {$this->translate('Exportar')} .MO</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <form role="form" id="frm-table-terms" action="{$hostPath}project/saveTermsLang" method="post">
            <input type="hidden" name="lang" value="{$lang}" />
            <table class="table" id="tbl-terms">
                <thead>
                    <tr>
                        <th width="4%">#</th>
                        <th width="43%">{$this->translate('Texto')}</th>
                        <th width="42%">{$this->translate('Tradução')}</th>
                        <th width="15%">{$this->translate('Opções')}</th>
                    </tr>
                </thead>
                <tbody>
                    {assign var=incTerm value=0}
                    {foreach from=$terms key=texto item=term}
                        <tr>
                            <td>
                                <a id="term_{$incTerm}" href="#term_{$incTerm++}" data-toggle="tooltip" title="{foreach from=$term.files key=file item=lines}{$file} {foreach from=$lines item=line} #{$line}{/foreach}<br />{/foreach}"><span class="glyphicon glyphicon-info-sign"></span></a>
                            </td>
                            <td class="term">
                                {$term.name} <input type="hidden" name="{$texto}" value="{$term.name}" />
                            </td>
                            <td>
                                <input name="t_{$texto}" id="{$texto}" {if isset($arrTranslateds.$texto)}value="{$arrTranslateds.$texto}"{/if} class="form-control" type="text" />
                            </td>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-primary"><span class="glyphicon glyphicon-cog"></span></button>
                                    <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-toggle="dropdown">
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a class="openGoogleOne"><span class="glyphicon glyphicon-globe"></span> {$this->translate('Traduzir Item')}</a></li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    {/foreach}
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="4">
                            <button class='btn btn-default pull-right'><span class="glyphicon glyphicon-save"></span> {$this->translate('Salvar')}</button>
                        </td>
                    </tr>
                </tfoot>
            </table>


        </form>
    </div>
</div>

<div class="modal fade" id="mdlGoogleAll" tabindex="-1" role="dialog" aria-labelledby="mdlNovoIdiomaLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">{$this->translate('Google Tradutor - Traduzir tudo')}</h4>
            </div>

            <div class="modal-body">
                <form role="form" method="post">
                    <div class="form-group">
                        <label>{$this->translate('Idioma Origem')}</label>
                        <select id="frk-lang-origem" name="frk-lang-origem" class="form-control">
                            <option value="">{$this->translate('Selecione')}</option>
                            {foreach from=$arrAllLangs item=label key=key}
                                <option {if $key == $langDefault}selected{/if} value="{$key}">{$label}</option>
                            {/foreach}
                        </select>
                    </div>
                    <div class="form-group">
                        <label>{$this->translate('Idioma Destino')}</label>
                        <select id="frk-lang-destino" name="frk-lang-destino" class="form-control">
                            <option value="">{$this->translate('Selecione')}</option>
                            {foreach from=$arrAllLangs item=label key=key}
                                <option {if $key == $lang}selected{/if} value="{$key}">{$label}</option>
                            {/foreach}
                        </select>
                    </div>
                </form>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{$this->translate('Fechar')}</button>
                <button type="button" id="btn-google-all" class="btn btn-primary">{$this->translate('Traduzir')}</button>
            </div>

        </div>
    </div>
</div>

<div class="modal fade" id="mdlGoogleOne" tabindex="-1" role="dialog" aria-labelledby="mdlNovoIdiomaLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">{$this->translate('Google Tradutor - Traduzir item')}</h4>
            </div>

            <div class="modal-body">
                <h4><i id='google-one-term'></i></h4><hr />
                <form role="form" method="post">
                    <div class="form-group">
                        <label>{$this->translate('Idioma Origem')}</label>
                        <select id="frk-lang-origem" name="frk-lang-origem" class="form-control">
                            <option value="">{$this->translate('Selecione')}</option>
                            {foreach from=$arrAllLangs item=label key=key}
                                <option {if $key == $langDefault}selected{/if} value="{$key}">{$label}</option>
                            {/foreach}
                        </select>
                    </div>
                    <div class="form-group">
                        <label>{$this->translate('Idioma Destino')}</label>
                        <select id="frk-lang-destino" name="frk-lang-destino" class="form-control">
                            <option value="">{$this->translate('Selecione')}</option>
                            {foreach from=$arrAllLangs item=label key=key}
                                <option {if $key == $lang}selected{/if} value="{$key}">{$label}</option>
                            {/foreach}
                        </select>
                    </div>
                </form>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{$this->translate('Fechar')}</button>
                <button type="button" id="btn-google-one" class="btn btn-primary">{$this->translate('Traduzir')}</button>
            </div>

        </div>
    </div>
</div>